services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.13.2'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'
  mysql:
    image: 'mysql:8.3.0'
    environment:
      MYSQL_DATABASE: webinar
      MY_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql-vol:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  mysql-vol:
    driver: local
