spring:
    application:
        name: elasticsearch-webinar
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    hibernate:
        ddl-auto: none
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
    elasticsearch:
        rest:
            port: 9200
            uris: http://localhost
    jpa:
        datasource:
            url: jdbc:mysql://localhost:3306/webinar?createDatabaseIfNotExist=true
            username: root
            password: root
            driver-class-name: com.mysql.cj.jdbc.Driver
    liquibase:
        contexts: default
        database-change-log-lock-table: ES_DATABASECHANGELOGLOCK
        database-change-log-table: ES_DATABASECHANGELOG
        url: jdbc:mysql://localhost:3306/webinar?createDatabaseIfNotExist=true
        default-schema: webinar
        user: root
        password: root
        enabled: true
